# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yzx/App/FHMF/src/Md5Gen

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yzx/App/FHMF/src/Md5Gen

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yzx/App/FHMF/src/Md5Gen/CMakeFiles /home/yzx/App/FHMF/src/Md5Gen//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yzx/App/FHMF/src/Md5Gen/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named md5gen

# Build rule for target.
md5gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 md5gen
.PHONY : md5gen

# fast build rule for target.
md5gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen.dir/build.make CMakeFiles/md5gen.dir/build
.PHONY : md5gen/fast

#=============================================================================
# Target rules for targets named md5gen_lib

# Build rule for target.
md5gen_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 md5gen_lib
.PHONY : md5gen_lib

# fast build rule for target.
md5gen_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen_lib.dir/build.make CMakeFiles/md5gen_lib.dir/build
.PHONY : md5gen_lib/fast

GetMd5File.o: GetMd5File.c.o
.PHONY : GetMd5File.o

# target to build an object file
GetMd5File.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen.dir/build.make CMakeFiles/md5gen.dir/GetMd5File.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen_lib.dir/build.make CMakeFiles/md5gen_lib.dir/GetMd5File.c.o
.PHONY : GetMd5File.c.o

GetMd5File.i: GetMd5File.c.i
.PHONY : GetMd5File.i

# target to preprocess a source file
GetMd5File.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen.dir/build.make CMakeFiles/md5gen.dir/GetMd5File.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen_lib.dir/build.make CMakeFiles/md5gen_lib.dir/GetMd5File.c.i
.PHONY : GetMd5File.c.i

GetMd5File.s: GetMd5File.c.s
.PHONY : GetMd5File.s

# target to generate assembly for a file
GetMd5File.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen.dir/build.make CMakeFiles/md5gen.dir/GetMd5File.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen_lib.dir/build.make CMakeFiles/md5gen_lib.dir/GetMd5File.c.s
.PHONY : GetMd5File.c.s

MakeMd5File.o: MakeMd5File.c.o
.PHONY : MakeMd5File.o

# target to build an object file
MakeMd5File.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen.dir/build.make CMakeFiles/md5gen.dir/MakeMd5File.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen_lib.dir/build.make CMakeFiles/md5gen_lib.dir/MakeMd5File.c.o
.PHONY : MakeMd5File.c.o

MakeMd5File.i: MakeMd5File.c.i
.PHONY : MakeMd5File.i

# target to preprocess a source file
MakeMd5File.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen.dir/build.make CMakeFiles/md5gen.dir/MakeMd5File.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen_lib.dir/build.make CMakeFiles/md5gen_lib.dir/MakeMd5File.c.i
.PHONY : MakeMd5File.c.i

MakeMd5File.s: MakeMd5File.c.s
.PHONY : MakeMd5File.s

# target to generate assembly for a file
MakeMd5File.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen.dir/build.make CMakeFiles/md5gen.dir/MakeMd5File.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen_lib.dir/build.make CMakeFiles/md5gen_lib.dir/MakeMd5File.c.s
.PHONY : MakeMd5File.c.s

md5gen.o: md5gen.c.o
.PHONY : md5gen.o

# target to build an object file
md5gen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen.dir/build.make CMakeFiles/md5gen.dir/md5gen.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen_lib.dir/build.make CMakeFiles/md5gen_lib.dir/md5gen.c.o
.PHONY : md5gen.c.o

md5gen.i: md5gen.c.i
.PHONY : md5gen.i

# target to preprocess a source file
md5gen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen.dir/build.make CMakeFiles/md5gen.dir/md5gen.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen_lib.dir/build.make CMakeFiles/md5gen_lib.dir/md5gen.c.i
.PHONY : md5gen.c.i

md5gen.s: md5gen.c.s
.PHONY : md5gen.s

# target to generate assembly for a file
md5gen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen.dir/build.make CMakeFiles/md5gen.dir/md5gen.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen_lib.dir/build.make CMakeFiles/md5gen_lib.dir/md5gen.c.s
.PHONY : md5gen.c.s

modules/CRC32.o: modules/CRC32.c.o
.PHONY : modules/CRC32.o

# target to build an object file
modules/CRC32.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen.dir/build.make CMakeFiles/md5gen.dir/modules/CRC32.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen_lib.dir/build.make CMakeFiles/md5gen_lib.dir/modules/CRC32.c.o
.PHONY : modules/CRC32.c.o

modules/CRC32.i: modules/CRC32.c.i
.PHONY : modules/CRC32.i

# target to preprocess a source file
modules/CRC32.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen.dir/build.make CMakeFiles/md5gen.dir/modules/CRC32.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen_lib.dir/build.make CMakeFiles/md5gen_lib.dir/modules/CRC32.c.i
.PHONY : modules/CRC32.c.i

modules/CRC32.s: modules/CRC32.c.s
.PHONY : modules/CRC32.s

# target to generate assembly for a file
modules/CRC32.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen.dir/build.make CMakeFiles/md5gen.dir/modules/CRC32.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen_lib.dir/build.make CMakeFiles/md5gen_lib.dir/modules/CRC32.c.s
.PHONY : modules/CRC32.c.s

modules/HashVal.o: modules/HashVal.c.o
.PHONY : modules/HashVal.o

# target to build an object file
modules/HashVal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen.dir/build.make CMakeFiles/md5gen.dir/modules/HashVal.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen_lib.dir/build.make CMakeFiles/md5gen_lib.dir/modules/HashVal.c.o
.PHONY : modules/HashVal.c.o

modules/HashVal.i: modules/HashVal.c.i
.PHONY : modules/HashVal.i

# target to preprocess a source file
modules/HashVal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen.dir/build.make CMakeFiles/md5gen.dir/modules/HashVal.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen_lib.dir/build.make CMakeFiles/md5gen_lib.dir/modules/HashVal.c.i
.PHONY : modules/HashVal.c.i

modules/HashVal.s: modules/HashVal.c.s
.PHONY : modules/HashVal.s

# target to generate assembly for a file
modules/HashVal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen.dir/build.make CMakeFiles/md5gen.dir/modules/HashVal.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen_lib.dir/build.make CMakeFiles/md5gen_lib.dir/modules/HashVal.c.s
.PHONY : modules/HashVal.c.s

modules/cJSON.o: modules/cJSON.c.o
.PHONY : modules/cJSON.o

# target to build an object file
modules/cJSON.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen.dir/build.make CMakeFiles/md5gen.dir/modules/cJSON.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen_lib.dir/build.make CMakeFiles/md5gen_lib.dir/modules/cJSON.c.o
.PHONY : modules/cJSON.c.o

modules/cJSON.i: modules/cJSON.c.i
.PHONY : modules/cJSON.i

# target to preprocess a source file
modules/cJSON.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen.dir/build.make CMakeFiles/md5gen.dir/modules/cJSON.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen_lib.dir/build.make CMakeFiles/md5gen_lib.dir/modules/cJSON.c.i
.PHONY : modules/cJSON.c.i

modules/cJSON.s: modules/cJSON.c.s
.PHONY : modules/cJSON.s

# target to generate assembly for a file
modules/cJSON.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen.dir/build.make CMakeFiles/md5gen.dir/modules/cJSON.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/md5gen_lib.dir/build.make CMakeFiles/md5gen_lib.dir/modules/cJSON.c.s
.PHONY : modules/cJSON.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... md5gen"
	@echo "... md5gen_lib"
	@echo "... GetMd5File.o"
	@echo "... GetMd5File.i"
	@echo "... GetMd5File.s"
	@echo "... MakeMd5File.o"
	@echo "... MakeMd5File.i"
	@echo "... MakeMd5File.s"
	@echo "... md5gen.o"
	@echo "... md5gen.i"
	@echo "... md5gen.s"
	@echo "... modules/CRC32.o"
	@echo "... modules/CRC32.i"
	@echo "... modules/CRC32.s"
	@echo "... modules/HashVal.o"
	@echo "... modules/HashVal.i"
	@echo "... modules/HashVal.s"
	@echo "... modules/cJSON.o"
	@echo "... modules/cJSON.i"
	@echo "... modules/cJSON.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

